project:
  type: website
  output-dir: docs   

website:
  title: "Payer Analysis For Healthcare Data In the USA"
<<<<<<< HEAD
  google-analytics: "G-WG7SCC1Z38" 
=======
  google-analytics: "G-WG7SCC1Z38"  
>>>>>>> 1ff362f00bb3d2c275b55784d35058ba8be08231
  navbar:
    left:
      - href: index.qmd
        text: "Overview"
      - href: insurance.qmd  
        text: "Insurance Coverage"
      - href: claims.qmd        
        text: "Claims Analysis"
      - href: onset.qmd         
        text: "Age of Onset"
      
format:
  html:
    theme: cyborg
    toc: true
